# Generated by Django 3.2.9 on 2023-08-29 00:08

from django.db import migrations, models
import resource.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, upload_to=resource.models.upload_to_images)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, upload_to=resource.models.upload_to_images)),
            ],
        ),
    ]
