# Generated by Django 3.2.9 on 2023-08-30 05:25

from django.db import migrations, models
import resource.models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, upload_to=resource.models.upload_to_images)),
            ],
        ),
    ]
