# Generated by Django 3.2.9 on 2023-08-30 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0002_trainclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_station', to='resource.station', verbose_name='from_station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='resource.station', verbose_name='to_station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.train')),
                ('train_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.trainclass')),
            ],
        ),
    ]
