# Generated by Django 3.2.9 on 2023-08-30 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_trainclass'),
        ('schedule', '0002_remove_schedule_train_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='train_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resource.trainclass'),
            preserve_default=False,
        ),
    ]
