# Generated by Django 3.2.9 on 2023-08-12 09:59

from django.db import migrations, models
import tutorials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, upload_to=tutorials.models.upload_to_images)),
            ],
        ),
    ]
